In [2]:
from datasets import load_dataset

ds = load_dataset("bitext/Bitext-telco-llm-chatbot-training-dataset")

c:\Users\sadny\Documents\GitHub\fine_tuning_telco\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\sadny\Documents\GitHub\fine_tuning_telco\.venv\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sadny\.cache\huggingface\hub\datasets--bitext--Bitext-telco-llm-chatbot-training-dataset. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 26000/26000 [00:00<00:00, 114808.88 examples/s]

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['instruction', 'intent', 'category', 'tags', 'response'],
        num_rows: 26000
    })
})

In [4]:
for i in range(5):
    print(f"\n{'='*80}")
    print(f"Sample {i}")
    print(f"{'='*80}")
    
    print("Instruction:")
    print(ds["train"][i]["instruction"])
    
    print("\nIntent:")
    print(ds["train"][i]["intent"])
    
    print("\nCategory:")
    print(ds["train"][i]["category"])
    
    print("\nTags:")
    print(ds["train"][i]["tags"])
    
    print("\nResponse:")
    print(ds["train"][i]["response"])

================================================================================
Sample 0
================================================================================
Instruction:
there are charges on my phone bill that i do not recogniae challenge it

Intent:
dispute_invoice

Category:
BILLING

Tags:
BCELQZ

Response:
If you have noticed discrepancies in your bill and wish to contest them, please adhere to the following steps:

1. Log in to your account on {{WEBSITE_URL}}.
2. Navigate to the {{INVOICE_SECTION}} section.
3. Select the bill you wish to dispute.
4. Click on the {{DISPUTE_INVOICE_OPTION}} to dispute the charge.
5. Fill in the required information and submit your dispute.

Our team will review your submission and get back to you within {{DAYS_NUMBER}} business days.

================================================================================
Sample 1
================================================================================
Instruction:
my internet bill is incorrect, can you help me dispute it ?

Intent:
dispute_invoice

Category:
BILLING

Tags:
BCILZ

Response:
If there is an issue with your bill and you would like to formally dispute it, please adhere to the following steps:

1. Log in to your account on {{WEBSITE_URL}}.
2. Navigate to the {{INVOICE_SECTION}} section.
3. Select the bill you wish to dispute.
4. Click on the {{DISPUTE_INVOICE_OPTION}} to dispute the charge.
5. Fill in the required information and submit your dispute.

Our team will review your submission and get back to you within {{DAYS_NUMBER}} business days.

================================================================================
Sample 2
================================================================================
Instruction:
my invoice is not corect challenge it

Intent:
dispute_invoice

Category:
BILLING

Tags:
BCELQZ

Response:
If you find any discrepancies in your invoice and wish to contest it, please adhere to the following steps:

1. Log in to your account on {{WEBSITE_URL}}.
2. Navigate to the {{INVOICE_SECTION}} section.
3. Select the bill you wish to dispute.
4. Click on the {{DISPUTE_INVOICE_OPTION}} to dispute the charge.
5. Fill in the required information and submit your dispute.

Our team will thoroughly examine your request and respond within {{DAYS_NUMBER}} business days.

================================================================================
Sample 3
================================================================================
Instruction:
I don't recognize some charges on my bill, can you help me appeal it?

Intent:
dispute_invoice

Category:
BILLING

Tags:
BCIL

Response:
If you have found charges on your bill that you believe are inaccurate and wish to dispute them, please adhere to the following steps:

1. Log in to your account on {{WEBSITE_URL}}.
2. Navigate to the {{INVOICE_SECTION}} section.
3. Select the bill you wish to dispute.
4. Click on the {{DISPUTE_INVOICE_OPTION}} to dispute the charge.
5. Fill in the required information and submit your dispute.

Our team will review your submission and get back to you within {{DAYS_NUMBER}} business days.

================================================================================
Sample 4
================================================================================
Instruction:
i have to dispute a fucking bill i need help

Intent:
dispute_invoice

Category:
BILLING

Tags:
BCQW

Response:
If you believe there is an error on your bill and would like to initiate a dispute, please follow these steps:

1. Log in to your account on {{WEBSITE_URL}}.
2. Navigate to the {{INVOICE_SECTION}} section.
3. Select the bill you wish to dispute.
4. Click on the {{DISPUTE_INVOICE_OPTION}} to dispute the charge.
5. Fill in the required information and submit your dispute.

Our team will review your submission and get back to you within {{DAYS_NUMBER}} business days.

In [5]:
print(ds["train"].features)

{'instruction': Value('string'), 'intent': Value('string'), 'category': Value('string'), 'tags': Value('string'), 'response': Value('string')}

In [6]:
sample = ds["train"][0]

for col, value in sample.items():
    print(f"\n{col}")
    print("Python type:", type(value))
    print("Value:", value)

instruction
Python type: <class 'str'>
Value: there are charges on my phone bill that i do not recogniae challenge it

intent
Python type: <class 'str'>
Value: dispute_invoice

category
Python type: <class 'str'>
Value: BILLING

tags
Python type: <class 'str'>
Value: BCELQZ

response
Python type: <class 'str'>
Value: If you have noticed discrepancies in your bill and wish to contest them, please adhere to the following steps:

1. Log in to your account on {{WEBSITE_URL}}.
2. Navigate to the {{INVOICE_SECTION}} section.
3. Select the bill you wish to dispute.
4. Click on the {{DISPUTE_INVOICE_OPTION}} to dispute the charge.
5. Fill in the required information and submit your dispute.

Our team will review your submission and get back to you within {{DAYS_NUMBER}} business days.

In [10]:
idx = 1009
row = ds["train"][idx]

for key, value in row.items():
    print(f"\n{key}:")
    print(value)

instruction:
I would like to check my fucking phone bills, could you help me?

intent:
invoices

category:
BILLING

tags:
BCILPW

response:
To assist you in reviewing your recent phone bills, please follow the steps below:

1. Visit {{WEBSITE_URL}}.
2. Navigate to the {{BILLING_SECTION}} section.
3. Select {{VIEW_PAST_BILLS}}.
4. Choose the bill for the month you wish to examine.

If you require any additional help, do not hesitate to reach out.

In [15]:
import pandas as pd
from collections import Counter
import re

word_counts = Counter()

for text in ds["train"]["instruction"]:
    words = re.findall(r"\b\w+\b", text.lower())
    word_counts.update(words)

df_words = pd.DataFrame(
    word_counts.items(),
    columns=["word", "count"]
).sort_values("count", ascending=False)

df_words.head(50)

             word  count
8               i  31052
30             to  21544
13             it  10349
9              do  10104
32        fucking   8681
19           help   8567
4              my   7278
20             me   6731
37           like   6459
17            can   5969
40          could   5920
47            how   5542
31              a   5490
33           need   5295
38          where   4040
36              d   3393
791        mobile   3274
63            get   3092
983           the   2973
76           want   2927
39            got   2859
29           have   2839
18            you   2827
5           phone   2741
344         about   2718
27           some   2677
14       internet   2507
343   information   2032
345           see   1960
1587         call   1915
66          would   1885
790          cell   1844
329         check   1834
52          wanna   1691
59             id   1657
49     assistance   1596
3              on   1588
41             ya   1510
1903     payments   1489
3225     contract   1423
2364     activate   1402
3230         plan   1384
43           will   1347
793        report   1337
789      coverage   1286
331          find   1216
989       service   1207
1131         data   1206
2         charges   1205
1307        usage   1167

In [17]:
from collections import Counter

intent_counts = Counter(ds["train"]["intent"])

print("Total unique intents:", len(intent_counts))
print()

for intent, count in intent_counts.most_common():
    print(f"{intent:<40} {count}")

Total unique intents: 26

dispute_invoice                          1000
invoices                                 1000
get_compensation                         1000
report_poor_signal_coverage              1000
report_problem                           1000
check_excess_data_charges                1000
check_usage                              1000
set_usage_limits                         1000
customer_service                         1000
human_agent                              1000
check_mobile_payments                    1000
payment_methods                          1000
pay                                      1000
schedule_payments                        1000
activate_call_management_services        1000
activate_phone                           1000
activate_roaming                         1000
check_signal_coverage                    1000
deactivate_call_management_services      1000
deactivate_phone                         1000
install_internet                         1000
cancel_plan                              1000
change_plan                              1000
change_provider                          1000
check_cancellation_fee                   1000
sign_up_for_plan                         1000

In [18]:
from collections import Counter
import re

for intent in sorted(set(ds["train"]["intent"])):

    words = Counter()

    rows = ds["train"].filter(
        lambda x: x["intent"] == intent
    )

    for text in rows["instruction"]:
        tokens = re.findall(r"\b\w+\b", text.lower())
        words.update(tokens)

    print(f"\n{'='*80}")
    print(intent)
    print(f"{'='*80}")

    for word, count in words.most_common(20):
        print(f"{word:<20} {count}")

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 149554.16 examples/s]

================================================================================
activate_call_management_services
================================================================================
i                    1468
call                 1026
to                   913
on                   463
do                   377
help                 364
enable               299
alert                298
waiting              292
it                   288
turn                 281
me                   272
activate             267
while                255
want                 250
need                 218
could                217
can                  194
like                 193
how                  184

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 156209.75 examples/s]

================================================================================
activate_phone
================================================================================
i                    1279
a                    917
activate             776
phone                698
it                   663
to                   591
new                  462
help                 369
me                   324
have                 289
got                  287
do                   267
tablet               256
bought               228
cell                 225
mobile               218
could                209
can                  209
need                 187
like                 158

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 170961.51 examples/s]

================================================================================
activate_roaming
================================================================================
i                    1201
roaming              904
on                   840
to                   826
phone                637
my                   631
do                   435
international        426
turn                 401
it                   393
activate             359
help                 301
like                 286
how                  247
could                244
can                  242
me                   236
mobile               209
cell                 199
where                179

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 122809.10 examples/s]

================================================================================
cancel_plan
================================================================================
i                    1159
my                   1079
to                   728
cancel               694
contract             521
fucking              445
mobile               414
plan                 414
do                   340
it                   292
how                  277
cell                 266
internet             264
help                 258
like                 227
losing               206
service              205
constantly           201
me                   188
can                  188

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 151594.68 examples/s]

================================================================================
change_plan
================================================================================
i                    1189
my                   973
to                   866
do                   485
plan                 473
change               456
contract             452
fucking              448
modify               433
it                   386
help                 357
cell                 340
mobile               303
internet             289
like                 247
me                   241
could                228
need                 228
how                  227
can                  194

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 133728.73 examples/s]

================================================================================
change_provider
================================================================================
to                   1275
i                    1196
provider             934
fucking              474
it                   474
do                   458
change               456
another              434
switch               425
the                  423
help                 356
mobile               284
internet             283
service              281
me                   260
like                 257
can                  247
how                  225
need                 220
could                212

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 140756.09 examples/s]

================================================================================
check_cancellation_fee
================================================================================
i                    1056
the                  965
to                   665
fees                 661
early                635
fucking              489
like                 362
exit                 339
about                335
do                   317
it                   309
information          299
fee                  297
check                285
termination          280
see                  280
cancellation         277
me                   255
can                  251
help                 249

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 152287.99 examples/s]

================================================================================
check_excess_data_charges
================================================================================
i                    1158
data                 947
excess               938
charges              925
to                   637
the                  497
fucking              482
about                424
information          386
it                   326
can                  289
like                 282
do                   267
could                250
see                  249
me                   248
check                246
help                 240
how                  231
where                202

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 153187.10 examples/s]

================================================================================
check_mobile_payments
================================================================================
i                    1113
mobile               928
payments             913
to                   842
fucking              452
see                  450
do                   447
check                427
it                   368
help                 330
me                   254
like                 247
can                  239
how                  204
need                 203
where                199
could                198
have                 133
d                    125
got                  123

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 141200.78 examples/s]

================================================================================
check_signal_coverage
================================================================================
i                    1156
to                   694
availability         558
about                390
information          344
like                 342
coverage             342
at                   337
home                 331
in                   330
my                   329
area                 325
fucking              306
it                   304
do                   288
fiber                285
check                270
see                  255
the                  252
could                250

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 154879.51 examples/s]

================================================================================
check_usage
================================================================================
i                    1175
my                   965
usage                933
to                   675
fucking              446
about                406
information          367
it                   338
like                 318
do                   295
could                266
can                  266
check                252
how                  249
see                  245
me                   236
help                 229
know                 209
where                192
get                  180

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 145821.73 examples/s]

================================================================================
customer_service
================================================================================
to                   1305
i                    1140
service              572
do                   465
it                   389
customer             373
fucking              370
support              367
help                 365
like                 263
me                   239
how                  221
can                  221
could                220
need                 218
email                217
send                 206
an                   198
contact              184
client               183

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 169580.41 examples/s]

================================================================================
deactivate_call_management_services
================================================================================
i                    1178
to                   885
call                 718
do                   470
it                   388
help                 358
off                  327
turn                 307
disable              286
deactivate           280
me                   258
like                 257
alert                244
services             232
management           230
can                  227
waiting              225
how                  219
need                 218
could                213

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 138558.84 examples/s]

================================================================================
deactivate_phone
================================================================================
i                    1176
a                    919
to                   890
deactivate           862
phone                714
do                   486
it                   400
help                 375
like                 265
me                   247
mobile               245
cell                 241
tablet               228
how                  228
could                222
need                 215
can                  215
where                168
have                 137
got                  137

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 145966.16 examples/s]

================================================================================
dispute_invoice
================================================================================
i                    1040
it                   705
bill                 689
to                   610
my                   479
do                   387
help                 379
me                   346
a                    345
on                   282
charges              275
dispute              274
appeal               272
recognize            266
invoice              265
challenge            249
internet             236
could                235
fucking              234
phone                223

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 162176.57 examples/s]

================================================================================
get_compensation
================================================================================
i                    1264
a                    925
compensation         905
to                   684
it                   516
fucking              446
get                  435
help                 369
receive              366
me                   305
need                 274
do                   263
could                239
can                  224
want                 195
how                  193
like                 143
an                   142
where                120
for                  114

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 138808.75 examples/s]

================================================================================
human_agent
================================================================================
i                    1315
to                   1213
a                    544
fucking              478
do                   453
with                 443
talk                 442
speak                390
understand           372
help                 339
agent                291
human                267
you                  262
it                   262
me                   255
could                198
can                  189
like                 185
how                  178
ya                   176

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 127603.84 examples/s]

================================================================================
install_internet
================================================================================
i                    1156
to                   907
my                   644
in                   643
up                   482
do                   470
the                  469
install              458
set                  457
fucking              456
it                   388
fiber                368
help                 363
new                  319
place                318
home                 317
me                   255
like                 248
could                230
how                  214

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 152773.99 examples/s]

================================================================================
invoices
================================================================================
i                    1291
my                   976
last                 578
to                   519
fucking              441
bills                413
it                   383
help                 364
me                   345
find                 309
month                293
bill                 283
can                  272
them                 258
could                250
phone                244
need                 231
internet             218
check                213
see                  208

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 117347.68 examples/s]

================================================================================
pay
================================================================================
i                    1154
to                   851
make                 794
do                   448
fucking              399
a                    391
it                   361
help                 353
like                 255
me                   244
could                230
can                  226
how                  220
need                 218
payments             208
transfers            203
payment              199
transfer             194
where                181
d                    138

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 156245.79 examples/s]

================================================================================
payment_methods
================================================================================
i                    1180
to                   778
payment              503
fucking              495
card                 443
pay                  416
do                   368
it                   359
like                 297
ur                   286
help                 281
options              264
can                  252
your                 243
methods              242
how                  239
with                 238
could                230
a                    228
me                   216

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 131551.56 examples/s]

================================================================================
report_poor_signal_coverage
================================================================================
i                    1152
poor                 958
signal               953
coverage             944
to                   901
about                481
do                   473
complain             453
report               449
it                   392
help                 354
internet             277
like                 277
me                   248
need                 234
cell                 232
how                  228
could                226
mobile               222
can                  205

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 164978.69 examples/s]

================================================================================
report_problem
================================================================================
i                    1197
report               888
to                   872
fucking              476
do                   455
a                    403
help                 379
it                   375
like                 257
me                   246
internet             236
the                  232
can                  231
need                 229
could                226
how                  209
problem              209
fault                196
problems             195
faults               190

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 136751.29 examples/s]

================================================================================
schedule_payments
================================================================================
i                    1182
to                   894
schedule             700
do                   437
fucking              395
transfers            371
it                   370
payments             368
help                 315
pay                  264
like                 255
how                  225
me                   222
need                 220
could                218
can                  213
up                   177
bill                 175
set                  171
automatic            167

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 110628.13 examples/s]

================================================================================
set_usage_limits
================================================================================
i                    1184
my                   976
to                   919
allowance            682
do                   495
fucking              464
set                  463
increase             449
it                   409
help                 366
like                 271
data                 255
me                   253
minutes              251
usage                234
how                  231
limits               230
could                230
can                  221
need                 218

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 138572.93 examples/s]

================================================================================
sign_up_for_plan
================================================================================
i                    1293
a                    787
to                   604
it                   511
plan                 497
fucking              475
contract             445
for                  376
cell                 337
mobile               319
help                 315
me                   294
internet             293
do                   281
can                  277
up                   258
could                251
sign                 230
need                 229
like                 226

In [19]:
categories = ds["train"]["category"]

unique_categories = sorted(set(categories))

print("Number of unique categories:", len(unique_categories))
print()

for category in unique_categories:
    print(category)

Number of unique categories: 7

BILLING
COMPLAINTS
CONSUMPTION
CONTACT
PAYMENT
SERVICES
SUBSCRIPTION

In [26]:
from collections import Counter
import re

for category in sorted(set(ds["train"]["category"])):

    words = Counter()

    rows = ds["train"].filter(
        lambda x: x["category"] == category
    )

    for text in rows["instruction"]:
        tokens = re.findall(r"\b\w+\b", text.lower())
        words.update(tokens)

    print(f"\n{'='*80}")
    print(category)
    print(f"{'='*80}")

    for word, count in words.most_common(30):
        print(f"{word:<30} {count}")

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 158887.88 examples/s]

================================================================================
BILLING
================================================================================
i                              2331
my                             1455
to                             1129
it                             1088
bill                           972
help                           743
me                             691
fucking                        675
last                           578
do                             564
can                            487
could                          485
phone                          467
internet                       454
bills                          413
need                           399
invoice                        364
a                              345
like                           341
find                           309
you                            301
how                            301
month                          293
on                             282
charges                        275
dispute                        274
appeal                         272
recognize                      266
some                           258
them                           258

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 132019.46 examples/s]

================================================================================
COMPLAINTS
================================================================================
i                              3613
to                             2457
report                         1337
a                              1328
it                             1283
do                             1191
help                           1102
poor                           958
signal                         953
coverage                       944
fucking                        922
compensation                   905
me                             799
need                           737
could                          691
like                           677
can                            660
how                            630
get                            624
internet                       592
about                          481
where                          459
complain                       453
want                           375
d                              371
receive                        366
mobile                         350
got                            342
have                           332
you                            300

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 168038.44 examples/s]

================================================================================
CONSUMPTION
================================================================================
i                              3517
to                             2231
my                             1942
fucking                        1392
data                           1206
usage                          1167
it                             1073
do                             1057
excess                         938
charges                        925
like                           871
help                           835
about                          830
can                            776
information                    753
could                          746
me                             737
how                            711
allowance                      682
where                          572
need                           515
check                          498
the                            497
see                            494
d                              464
set                            463
get                            455
increase                       449
some                           435
know                           405

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 164322.65 examples/s]

================================================================================
CONTACT
================================================================================
to                             2518
i                              2455
do                             918
fucking                        848
help                           704
it                             651
talk                           618
with                           605
a                              573
service                        572
speak                          542
me                             494
like                           448
could                          418
can                            410
how                            399
need                           385
customer                       373
understand                     372
support                        367
an                             359
you                            357
agent                          291
human                          267
where                          263
d                              234
ya                             230
got                            227
email                          217
have                           215

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 122865.69 examples/s]

================================================================================
PAYMENT
================================================================================
i                              4629
to                             3365
fucking                        1741
do                             1700
payments                       1489
it                             1458
help                           1279
like                           1054
me                             936
can                            930
mobile                         928
how                            888
could                          876
need                           834
make                           794
pay                            781
where                          712
payment                        706
schedule                       700
a                              619
see                            592
transfers                      574
check                          568
d                              561
got                            466
have                           465
card                           443
want                           406
get                            393
some                           379

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 123548.88 examples/s]

================================================================================
SERVICES
================================================================================
i                              8614
to                             5706
it                             2824
do                             2793
help                           2369
phone                          2138
a                              1838
me                             1836
like                           1749
call                           1744
my                             1693
could                          1585
can                            1549
how                            1462
activate                       1402
need                           1375
on                             1303
deactivate                     1142
where                          1081
got                            1028
have                           997
turn                           989
in                             973
roaming                        904
d                              883
the                            853
want                           811
new                            781
fucking                        772
you                            720

Filter: 100%|██████████| 26000/26000 [00:00<00:00, 151787.95 examples/s]

================================================================================
SUBSCRIPTION
================================================================================
i                              5893
to                             4138
fucking                        2331
my                             2147
it                             1972
do                             1881
help                           1535
contract                       1423
the                            1388
plan                           1384
mobile                         1320
like                           1319
me                             1238
can                            1157
how                            1151
internet                       1129
could                          1119
need                           1050
cell                           947
provider                       934
change                         912
a                              787
where                          760
cancel                         694
d                              686
fees                           661
early                          635
want                           614
about                          551
get                            509

In [27]:
tags = ds["train"]["tags"]

unique_tags = sorted(set(tags))

print("Number of unique categories:", len(unique_tags))
print()

for tag in unique_tags:
    print(tag)

Number of unique categories: 343

B
BC
BCE
BCEI
BCEIL
BCEILM
BCEILMPQW
BCEILMPQWZ
BCEILMPWZ
BCEILMQ
BCEILMQWZ
BCEILMW
BCEILP
BCEILPQ
BCEILPQW
BCEILPQWZ
BCEILPQZ
BCEILPW
BCEILPWZ
BCEILPZ
BCEILQ
BCEILQW
BCEILQWZ
BCEILQZ
BCEILW
BCEILWZ
BCEILZ
BCEIP
BCEIPQ
BCEIPQW
BCEIPQWZ
BCEIPQZ
BCEIPW
BCEIPWZ
BCEIPZ
BCEIQ
BCEIQW
BCEIQWZ
BCEIQZ
BCEIW
BCEIWZ
BCEIZ
BCEL
BCELMQWZ
BCELMWZ
BCELP
BCELPQ
BCELPQW
BCELPQWZ
BCELPQZ
BCELPWZ
BCELPZ
BCELQ
BCELQW
BCELQWZ
BCELQZ
BCELW
BCELWZ
BCELZ
BCEMP
BCEMQWZ
BCEP
BCEPQ
BCEPQWZ
BCEPQZ
BCEPZ
BCEQ
BCEQW
BCEQWZ
BCEQZ
BCEW
BCEWZ
BCEZ
BCI
BCIL
BCILM
BCILMP
BCILMPQ
BCILMPQW
BCILMPQWZ
BCILMPQZ
BCILMPW
BCILMPWZ
BCILMPZ
BCILMQ
BCILMQW
BCILMQWZ
BCILMQZ
BCILMW
BCILMWZ
BCILMZ
BCILP
BCILPQ
BCILPQW
BCILPQWZ
BCILPQZ
BCILPW
BCILPWZ
BCILPZ
BCILQ
BCILQW
BCILQWZ
BCILQZ
BCILW
BCILWZ
BCILZ
BCIM
BCIMP
BCIMPQ
BCIMPQW
BCIMPQWZ
BCIMPQZ
BCIMPW
BCIMPWZ
BCIMPZ
BCIMQ
BCIMQW
BCIMQWZ
BCIMQZ
BCIMW
BCIMWZ
BCIMZ
BCIP
BCIPQ
BCIPQW
BCIPQWZ
BCIPQZ
BCIPW
BCIPWZ
BCIPZ
BCIQ
BCIQW
BCIQWZ
BCIQZ
BCIW
BCIWZ
BCIZ
BCL
BCLM
BCLMP
BCLMPQ
BCLMPQW
BCLMPQWZ
BCLMPQZ
BCLMPW
BCLMPWZ
BCLMPZ
BCLMQ
BCLMQW
BCLMQWZ
BCLMQZ
BCLMW
BCLMWZ
BCLMZ
BCLP
BCLPQ
BCLPQW
BCLPQWZ
BCLPQZ
BCLPW
BCLPWZ
BCLPZ
BCLQ
BCLQW
BCLQWZ
BCLQZ
BCLW
BCLWZ
BCLZ
BCM
BCMP
BCMPQ
BCMPQW
BCMPQWZ
BCMPQZ
BCMPW
BCMPWZ
BCMPZ
BCMQ
BCMQW
BCMQWZ
BCMQZ
BCMW
BCMWZ
BCMZ
BCP
BCPQ
BCPQW
BCPQWZ
BCPQZ
BCPW
BCPWZ
BCPZ
BCQ
BCQW
BCQWZ
BCQZ
BCW
BCWZ
BCZ
BE
BEL
BELMQ
BELMQW
BELQ
BELQWZ
BELQZ
BELW
BELWZ
BELZ
BEQ
BEQW
BEQWZ
BEQZ
BEW
BEWZ
BEZ
BI
BIL
BILM
BILMP
BILMPQ
BILMPQW
BILMPQWZ
BILMPQZ
BILMPW
BILMPWZ
BILMPZ
BILMQ
BILMQW
BILMQWZ
BILMQZ
BILMW
BILMWZ
BILMZ
BILP
BILPQ
BILPQW
BILPQWZ
BILPQZ
BILPW
BILPWZ
BILPZ
BILQ
BILQW
BILQWZ
BILQZ
BILW
BILWZ
BILZ
BIM
BIMP
BIMPQ
BIMPQW
BIMPQWZ
BIMPQZ
BIMPW
BIMPWZ
BIMPZ
BIMQ
BIMQW
BIMQWZ
BIMQZ
BIMW
BIMWZ
BIMZ
BIP
BIPQ
BIPQW
BIPQWZ
BIPQZ
BIPW
BIPWZ
BIPZ
BIQ
BIQW
BIQWZ
BIQZ
BIW
BIWZ
BIZ
BL
BLM
BLMP
BLMPQ
BLMPQW
BLMPQWZ
BLMPQZ
BLMPW
BLMPZ
BLMQ
BLMQW
BLMQWZ
BLMQZ
BLMW
BLMWZ
BLMZ
BLP
BLPQ
BLPQW
BLPQWZ
BLPQZ
BLPW
BLPWZ
BLPZ
BLQ
BLQW
BLQWZ
BLQZ
BLW
BLWZ
BLZ
BM
BMP
BMPQ
BMPQW
BMPQWZ
BMPQZ
BMPW
BMPWZ
BMPZ
BMQ
BMQW
BMQWZ
BMQZ
BMW
BMWZ
BMZ
BP
BPQ
BPQW
BPQWZ
BPQZ
BPW
BPWZ
BPZ
BQ
BQW
BQWZ
BQZ
BW
BWZ
BZ

In [28]:

word_counts = Counter()

for text in ds["train"]["response"]:
    words = re.findall(r"\b\w+\b", text.lower())
    word_counts.update(words)

df_words = pd.DataFrame(
    word_counts.items(),
    columns=["word", "count"]
).sort_values("count", ascending=False)

df_words.head(50)

            word   count
10            to  137677
15           the  128843
6           your   81047
1            you   43334
13        please   34338
8            and   31751
151          for   27867
5             in   26273
23             2   26000
30             4   26000
27             3   26000
18             1   26000
26       section   24108
22   website_url   24000
60           any   23270
17         steps   22986
21            on   21235
0             if   20973
20       account   20375
24      navigate   20076
28        select   19896
39           our   18024
161      support   16556
19           log   15979
128          out   15040
34             5   15000
75        follow   14903
127        reach   14558
106   assistance   14479
198           or   14394
16     following   14314
92           not   12879
154   additional   12863
91            do   12706
14        adhere   12434
217       option   12147
54          with   12124
155     hesitate   11952
147        visit   11283
105      require   11249
150       choose   11085
135      details   10980
186      further   10816
123           of   10669
74             a   10467
620      payment   10019
40          team    9403
37   information    9345
393     customer    9018
226      service    8544